services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  activemq-artemis:
    image: apache/activemq-artemis:latest
    ports:
      - "8161:8161"  # Web console port
      - "61616:61616" # Messaging port
    volumes:
      - artemis-data:/var/lib/artemis-instance  # Persist data

volumes:
  mysql:
  artemis-data: