management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
    root: info
    edu.miu.cs544.moe.emr: debug
spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis