management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
    root: info
    edu.miu.cs544.moe.emr: debug
app:
  messaging:
    queue: emr.reports
  security:
    cors:
      origins: "*"
    jwt:
      secret: +NYuD2psQg62/zjjXB6LWtqPTg03hnrmBycSiuCXEtqFW5FtnRIR442y7KtZQROUuZ091vW00KS1TbtSDnn8mw==
      expiration: 3600000 # 1 hour
      refresh-token:
        expiration: 86400000 # 1 day
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
  datasource:
    username: admin
    password: password
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true